{
 "title": "Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "主节点组件状态",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)"
    }
   ]
  },
  {
   "title": "System Pods Crashed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts{namespace=~\"kube-system\"}[1h]) > 5)"
    }
   ]
  },
  {
   "title": "内存压力告警",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "App 数量概览",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"default\"})/6",
     "legendFormat": "App Expected"
    },
    { "legendFormat": "App Ready" },
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\".*-php-.*\"}[1h]) > 5)",
     "legendFormat": "Php Crashed"
    },
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\".*-node-.*\"}[1h]) > 5)",
     "legendFormat": "Node Crashed"
    },
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\".*-mongo-.*\"}[1h]) > 5)",
     "legendFormat": "Mongo Crashed"
    },
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\".*-mysql-.*\"}[1h]) > 5)",
     "legendFormat": "Mysql Crashed"
    },
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\".*-redis-.*\"}[1h]) > 5)",
     "legendFormat": "Redis Crashed"
    },
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\".*-rabbitmq-.*\"}[1h]) > 5)",
     "legendFormat": "Rabbitmq Crashed"
    }
   ]
  },
  {
   "title": "Expected Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=\"kube-system\"})+sum(kube_daemonset_status_desired_number_scheduled{namespace=\"kube-system\"})+sum(kube_statefulset_replicas{namespace=\"kube-system\"})+4"
    }
   ]
  },
  {
   "title": "System Pods Ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"kube-system\", condition=\"true\"})"
    }
   ]
  },
  {
   "title": "磁盘压力告警",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Pod 使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"default\"}) / sum(kube_resourcequota{namespace=\"default\", resource=\"count/deployments.extensions\", type=\"hard\"})"
    }
   ]
  },
  {
   "title": "Apps Capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"default\", resource=\"count/deployments.extensions\", type=\"hard\"})/6"
    }
   ]
  },
  {
   "title": "Expected Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "Pods Crashed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Pods Evicted",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Evicted\"})"
    }
   ]
  },
  {
   "title": "Nodes Number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Node CPU 负载",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "App Number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"default\"})/6"
    }
   ]
  },
  {
   "title": "Pods Ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"default\", condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase!=\"Running\"})"
    }
   ]
  },
  {
   "title": "Nodes Unscheduled",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Pod CPU 使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Pod CPU 使用概览",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "请求的核数"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_cpu_cores) by (instance))",
     "legendFormat": "限制的核数"
    },
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "可分配的核数"
    },
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores) by(instance)",
     "legendFormat": "总核数"
    }
   ]
  },
  {
   "title": "CPU 核使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)/sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Nodes CPU核数使用概览",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "可分配的CPU核数"
    },
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "Node CPU 空闲",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode=\"idle\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "Pod 内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Pod 内存使用概览",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "分配的内存"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "请求的内存"
    }
   ]
  },
  {
   "title": "Nodes 内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal))"
    }
   ]
  },
  {
   "title": "Nodes 内存使用概览",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(node_memory_MemTotal)", "legendFormat": "总内存" },
    { "expr": "sum(node_memory_MemAvailable)", "legendFormat": "可用内存" },
    { "expr": "sum(node_memory_Cached)", "legendFormat": "已缓存" },
    { "expr": "sum(node_memory_MemFree)", "legendFormat": "未用内存" }
   ]
  },
  {
   "title": "Node 网络发送数据量",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "磁盘 I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_ms[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "API Server 请求错误率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100"
    }
   ]
  },
  {
   "title": "API Server 请求速率",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code!~\"2..\"}[5m]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Node 网络接收数据量",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}