{
 "title": "Node CPU Utilization Details (Cores)",
 "description": "This is experimental dashboard for Percona Monitoring and Management (PMM) which provides CPU utilization details for multi-core systems.  It allows to easily see if overall CPU usage is high or if there are overloaded cores.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_uname_info, nodename)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_uname_info{nodename=\"$node\"}, instance)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu{instance=\"$host\"}, cpu)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Overall CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max Core Utilization"
      }
     ]
    },
    {
     "title": "$host - Current CPU Core Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "clamp_max(avg by () (sum by (cpu) ( (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Avg"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "{{cpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall CPU Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "All Cores - total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"user\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"system\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "CPU Cores Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Core CPU Usage",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
     "content": "Per CPU usage Information shows  usage for each CPU (Virtual) core.  The Current (most recent) numbers are shown together with history as sparkline"
    }
   ]
  },
  { "title": "Per Core Usage Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "cpu" },
  {
   "title": "$cpu - total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - steal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  }
 ]
}